cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'vitorgalvao/tiny-scripts'

# Tools
brew 'ffmpeg'
brew 'git'
brew 'hh'
brew 'imagemagick'
brew 'mas'
brew 'python'
brew 'rbenv'
brew 'youtube-dl'
brew 'duti'
brew 'ack'
brew 'fd'
brew 'ripgrep'
brew 'thefuck'
brew 'unrar'
brew 'p7zip'

# Non-MAS apps
cask '1password'
cask 'alfred'
cask 'balsamiq-mockups'
cask 'bartender'
cask 'base'
cask 'bettertouchtool'
cask 'boom'
cask 'cloak'
cask 'daisydisk'
cask 'dropbox'
cask 'gnucash'
cask 'hazel'
cask 'flux'
cask 'iterm2'
cask 'little-snitch'
cask 'kaleidoscope'
cask 'mailmate'
cask 'nvalt'
cask 'omnigraffle'
cask 'sublime-text'
cask 'ynab'

